version: '3'

services:
  db:
    container_name: db
    image: mysql/mysql-server:latest
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'django'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'Ipad3007'
       MYSQL_ROOT_PASSWORD: 'Ipad3007'
  web:
    container_name: web
    build: .
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
