# Generated by Django 5.0.3 on 2024-03-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_connect_expertinterview_itnews_jobsearch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='connect',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='connect',
            name='title_en',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='connect',
            name='title_ru',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='expertinterview',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expertinterview',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expertinterview',
            name='title_en',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='expertinterview',
            name='title_ru',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='itnews',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itnews',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itnews',
            name='title_en',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='itnews',
            name='title_ru',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='title_en',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='title_ru',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='professionalgrowth',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professionalgrowth',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professionalgrowth',
            name='title_en',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='professionalgrowth',
            name='title_ru',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='skilldevelopment',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skilldevelopment',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skilldevelopment',
            name='title_en',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='skilldevelopment',
            name='title_ru',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
