# Generated by Django 5.0.3 on 2024-03-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
    ]
