# Generated by Django 5.0.3 on 2024-03-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
