# Generated by Django 5.0.3 on 2024-03-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
